name: CASE Validation

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Get the code from the repository to be packaged
      - name: Get Repo
        uses: actions/checkout@v2

      # Setup the Python environment
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Run the CASE validation job to confirm all of the examples in examples/ are valid CASE.
      # Note, this only runs against files with the extension "jsonld"
      - name: CASE Export Validation
        uses: kchason/case-validation-action@v2.1
        with:
          case-path: ./examples/
          case-version: "case-0.6.0"
          extension-filter: "jsonld"
          